# -*- coding: utf-8 -*-
"""
Pre-filtre des transcriptions Claude Code. Phase 2 bis du Plan Jarvis.

Deterministe, aucun appel a un modele. Il lit les .jsonl bruts, jette tout
ce qui n'est ni une phrase de Souleman ni une reponse de Claude, et ecrit
un fichier de travail lisible par session.

Il ne modifie ni ne supprime aucun .jsonl. Il ne lit que.

Usage :
    python prefiltre.py <dossier_travail> <marqueur.txt> [borne_haute_iso]

La borne haute sert au rattrapage historique, pour traiter par lots.
"""

import json
import os
import re
import sys
import glob

PROJETS = os.path.expanduser(r"~\.claude\projects")
METAS = os.path.expanduser(r"~\AppData\Roaming\Claude\claude-code-sessions")

# Blocs injectes par le harnais, jamais ecrits par Souleman.
PARASITES = [
    re.compile(r"<system-reminder>.*?</system-reminder>", re.S),
    re.compile(r"<task-notification>.*?</task-notification>", re.S),
    re.compile(r"<local-command-stdout>.*?</local-command-stdout>", re.S),
    re.compile(r"<local-command-stderr>.*?</local-command-stderr>", re.S),
    re.compile(r"<command-message>.*?</command-message>", re.S),
    re.compile(r"<user-prompt-submit-hook>.*?</user-prompt-submit-hook>", re.S),
]

# Une commande lancee reste une information. On la reduit a une ligne.
RE_CMD_NOM = re.compile(r"<command-name>(.*?)</command-name>", re.S)
RE_CMD_ARGS = re.compile(r"<command-args>(.*?)</command-args>", re.S)
RE_BALISE = re.compile(r"</?[a-z][a-z0-9-]*>")

CAVEAT = "Caveat: The messages below were generated by the user while running"

# Les passages automatiques du coffre. Les relire ferait grossir une boucle
# ou l'extracteur se lit lui-meme chaque nuit, pour ne rien en tirer.
AUTOMATES = (
    "Obsidian\\transcriptions\\consigne.md",
    "Obsidian\\bibliothecaire\\consigne.md",
)


def nettoyer(txt):
    """Retire les blocs systeme d'un message utilisateur."""
    nom = RE_CMD_NOM.search(txt)
    args = RE_CMD_ARGS.search(txt)
    for p in PARASITES:
        txt = p.sub("", txt)
    txt = RE_CMD_ARGS.sub("", txt)
    txt = RE_BALISE.sub("", txt)
    txt = txt.strip()
    if nom:
        entete = nom.group(1).strip()
        if args and args.group(1).strip():
            entete += " " + args.group(1).strip()
        txt = (entete + "\n" + txt).strip()
    if txt.startswith(CAVEAT):
        return ""
    return txt


def titres():
    """Titres auto des sessions, donnes par l'app Claude. Absents sans gravite."""
    d = {}
    for f in glob.glob(os.path.join(METAS, "*", "*", "local_*.json")):
        try:
            with open(f, encoding="utf8") as fh:
                m = json.load(fh)
        except Exception:
            continue
        cli = m.get("cliSessionId")
        t = m.get("title")
        if cli and t:
            d[cli] = t
    return d


def sain(nom):
    """Nom de fichier acceptable par Windows."""
    nom = re.sub(r'[<>:"/\|?*]', " ", nom)
    nom = re.sub(r"\s+", " ", nom).strip()
    return nom[:70]


def lire(chemin, depuis, jusqu):
    """Extrait les tours de parole d'une session dans la fenetre demandee."""
    tours = []
    vu = set()
    try:
        fh = open(chemin, encoding="utf8", errors="replace")
    except Exception:
        return tours, vu
    with fh:
        for ligne in fh:
            try:
                d = json.loads(ligne)
            except Exception:
                continue
            if d.get("isSidechain"):
                continue          # travail d'un sous-agent, pas une parole
            ts = d.get("timestamp")
            if not ts:
                continue
            if depuis and ts <= depuis:
                continue
            if jusqu and ts > jusqu:
                continue
            m = d.get("message")
            if not isinstance(m, dict):
                continue
            vu.add(ts)
            if d.get("type") == "user":
                c = m.get("content")
                if not isinstance(c, str):
                    continue      # resultat d'outil, pas une phrase
                t = nettoyer(c)
                if t:
                    tours.append(("Souleman", ts, t))
            elif d.get("type") == "assistant":
                c = m.get("content")
                if not isinstance(c, list):
                    continue
                bouts = [b.get("text", "") for b in c
                         if isinstance(b, dict) and b.get("type") == "text"]
                t = "\n".join(x for x in bouts if x.strip()).strip()
                if t:
                    tours.append(("Claude", ts, t))
    # Un automate se reconnait a son premier tour, qui est sa ligne de
    # lancement et rien d'autre. Chercher le chemin n'importe ou exclurait
    # a tort les sessions ou Souleman parle de ces scripts.
    if tours:
        tete = tours[0][2]
        if tete.startswith("Lis le fichier ") and any(a in tete for a in AUTOMATES):
            return [], vu
    return tours, vu


def main():
    if len(sys.argv) < 3:
        print("usage: prefiltre.py <dossier_travail> <marqueur> [borne_haute]")
        return 2
    travail = sys.argv[1]
    marqueur = sys.argv[2]
    jusqu = sys.argv[3] if len(sys.argv) > 3 else None

    depuis = ""
    if os.path.exists(marqueur):
        with open(marqueur, encoding="utf-8-sig") as fh:
            depuis = fh.read().strip()

    os.makedirs(travail, exist_ok=True)
    for f in glob.glob(os.path.join(travail, "*.md")):
        os.remove(f)          # copies derivees, regenerables

    tt = titres()
    nb = 0
    octets = 0
    maxi = depuis

    for chemin in sorted(glob.glob(os.path.join(PROJETS, "*", "*.jsonl"))):
        sid = os.path.basename(chemin)[:-6]
        tours, vu = lire(chemin, depuis, jusqu)
        for ts in vu:
            if ts > maxi:
                maxi = ts
        if not tours:
            continue
        date = tours[0][1][:10]
        titre = tt.get(sid, "Session sans titre")
        corps = [
            "# " + titre,
            "session: " + sid[:8],
            "date: " + date,
            "transcription: " + chemin,
            "",
        ]
        for qui, ts, txt in tours:
            corps.append("--- " + qui + ", " + ts[:16].replace("T", " ") + " ---")
            corps.append(txt)
            corps.append("")
        texte = "\n".join(corps)
        nom = date + " " + sid[:8] + " " + sain(titre) + ".md"
        with open(os.path.join(travail, nom), "w", encoding="utf8") as fh:
            fh.write(texte)
        nb += 1
        octets += len(texte.encode("utf8"))

    with open(os.path.join(travail, "resultat.txt"), "w", encoding="utf8") as fh:
        fh.write("sessions=%d\n" % nb)
        fh.write("octets=%d\n" % octets)
        fh.write("depuis=%s\n" % (depuis or "origine"))
        fh.write("maxi=%s\n" % maxi)
    print("sessions=%d octets=%d maxi=%s" % (nb, octets, maxi))
    return 0


if __name__ == "__main__":
    sys.exit(main())
